
mkdir -p llvm
cd llvm

cmake "$1" \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=output \
	-DLLVM_TARGETS_TO_BUILD=X86 \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DLLVM_INCLUDE_EXAMPLES=OFF \
	-DLLVM_BUILD_DOCS=OFF \
	-DLLVM_ENABLE_RTTI=ON \
	-DLLVM_ENABLE_OCAMLDOC=OFF \
	-DLLVM_ENABLE_BINDINGS=OFF \
	-DLLVM_BUILD_LLVM_DYLIB=OFF


