
mkdir -p llvm
cd llvm

cmake "$1" \
	-DCMAKE_TOOLCHAIN_FILE="$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake" \
	-DANDROID_ABI=arm64-v8a \
	-DANDROID_STL=c++_static \
	-DLLVM_TARGETS_TO_BUILD=AArch64 \
	-DLLVM_TARGET_ARCH=AArch64 \
	-DANDROID_PLATFORM=android-26 \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=output \
	-DLLVM_ENABLE_THREADS=OFF \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DLLVM_INCLUDE_EXAMPLES=OFF \
	-DLLVM_BUILD_DOCS=OFF \
	-DLLVM_ENABLE_RTTI=ON \
	-DLLVM_ENABLE_OCAMLDOC=OFF \
	-DLLVM_ENABLE_BINDINGS=OFF \
	-DLLVM_BUILD_LLVM_DYLIB=OFF


